name: httpz-gateway

services:
  anvil-node:
    container_name: anvil-node
    image: ghcr.io/foundry-rs/foundry:stable
    env_file:
      - ./.env.example.deployment
    entrypoint:
      [
        "anvil",
        "--block-time",
        "0.1",
        "--host",
        "0.0.0.0",
        "--port",
        "8546",
        "--chain-id",
        "54321",
        "--accounts",
        "15",
        "--mnemonic",
        "${MNEMONIC}",
      ]
    ports:
      - "8546:8546"
    volumes:
      - .:/anvil

  sc-deploy:
    container_name: httpz-gateway-sc-deploy
    image: ghcr.io/zama-ai/gateway-l2/sc-bundle:0.1.0-local
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/zama-ai/gateway-l2/sc-bundle:0.1.0-local
    volumes:
      - ./.env.example.deployment:/app/.env
    entrypoint: ["/app/deploy-httpz-gateway-deployment.sh"]
    command: ["staging"]

  sc-deploy-debug:
    container_name: httpz-gateway-sc-deploy-debug
    image: ghcr.io/zama-ai/gateway-l2/sc-bundle:0.1.0-local
    volumes:
      - ./.env.example.deployment:/app/.env
    entrypoint: ["/bin/bash"]
    command: ["-c", "tail -f /dev/null"]
