name: Fhevm Gateway Mock Contracts Deployment

on:
  pull_request:
    paths-ignore:
      - "rust_bindings/**"
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fhevm-gateway-mock-contracts-deploy:
    name: Fhevm Gateway Mock Contracts Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
      - name: Login to Docker Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and start Docker services
        run: |
          make docker-compose-build
          make docker-compose-up

      - name: Check mock smart contract deployment
        run: |

          ## Check Mock contracts deployment
          timeout 300s bash -c 'while docker ps --filter "name=deploy-gateway-mock-contracts" --format "{{.Status}}" | grep -q "Up"; do sleep 5; done'
          docker compose logs deploy-gateway-mock-contracts > mock_contracts_deployment_logs.txt
          EXIT_CODE_SC=$(docker inspect --format='{{.State.ExitCode}}' deploy-gateway-mock-contracts)
          # display logs for debugging
          # cat mock_contracts_deployment_logs.txt
          if [ "$EXIT_CODE_SC" -ne 0 ]; then
            echo "Mock contract deployment failed with exit code $EXIT_CODE_SC"
            exit 1
          elif ! grep -q "Mock contract deployment done!" mock_contracts_deployment_logs.txt; then
            echo "Mock contract deployment did not complete successfully - 'Mock contract deployment done!' message not found in logs"
            exit 1
          else
            echo "Mock contract deployment completed successfully with expected completion message"
          fi

      - name: Clean up
        if: always()
        run: |
          make docker-compose-down

permissions:
  contents: read
  checks: write
  packages: read
