# This workflow verifies that:
# - The Rust bindings crate version and files are up-to-date
# - Contract mocks and selectors are current
# - Dependency licenses compliance
name: "Contract integrity checks"

on:
  pull_request:

  push:
    branches:
      - main

concurrency:
  group: contract-integrity-checks-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  contract-integrity-checks:
    name: Contract integrity checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Cache npm
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@de808b1eea699e761c404bda44ba8f21aba30b2c # v1.3.1
        with:
          version: v1.1.0

      - name: Install dependencies
        run: npm ci

      - name: Check bindings are up-to-date
        run: make check-bindings

      - name: Check contract selectors are up-to-date
        run: make check-selectors

      - name: Check mock contracts are up-to-date
        run: make check-mocks

      - name: Check licenses compliance
        run: make check-licenses
