name: "Docker - fhevm Node Golden Image"

on:
  pull_request:
    paths:
      - docker/base/Dockerfile
      - ../.github/workflows/docker-node-golden-image.yml
  push:
    branches:
      - main
    paths:
      - docker/base/Dockerfile
      - ../.github/workflows/docker-node-golden-image.yml
  release:
    types:
      - published

concurrency:
  group: node-golden-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  docker-node-golden:
    uses: zama-ai/fhevm-templates/.github/workflows/docker_common.yml@58ddd70781d1456d7fe937efef501a7bc5ca2d8d # main
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    with:
      working-directory: "."
      push_image: true
      image-name: "fhevm-node"
      docker-file: "docker/base/Dockerfile"
      arm-build: true