name: "Docker - fhevm Gateway Contracts"

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

concurrency:
  group: gateway-sc-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  docker-sc-bundle:
    name: Docker - fhevm Gateway Contracts
    uses: zama-ai/ci-templates/.github/workflows/docker_common.yml@44333c96991d6747e0bef6a3308bfd98b20390f8 # main
    secrets:
      GHCR_ACTION_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    with:
      working-directory: "."
      push_image: true
      image-name: "fhevm-gateway/contracts"
      docker-file: "Dockerfile"
      arm-build: true

  docker-hardhat-test:
    name: Run Hardhat tests with built image
    uses: ./.github/workflows/docker-hardhat-tests.yml
    with:
      image-name: ${{ needs.docker-sc-bundle.outputs.image_name }}
    needs:
      - docker-sc-bundle
