name: "Gateway Layer 2 sc Docker Image And Tests"

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

concurrency:
  group: gateway-sc-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  docker-sc-bundle:
    uses: ./.github/workflows/common-docker.yml
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    with:
      working-directory: "."
      push_image: true
      image-name: "gateway-l2/sc-bundle"
      docker-file: "Dockerfile"
      arm-build: true

    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}

  docker-test:
    uses: ./.github/workflows/docker-tests.yml
    with:
      image-name: ${{ needs.docker-sc-bundle.outputs.image_name }}
    needs:
      - docker-sc-bundle

  done:
    runs-on: ubuntu-latest
    name: Docker Pipeline Done
    steps:
      - name: Success
        run: echo Docker Pipeline Done
    needs:
      - docker-test
