[package]
authors = ["Zama"]
name = "httpz_gateway_rust_bindings"
publish = true
edition = "2024"
license = "BSD-3-Clause-Clear"
version = "1.0.0"

[dependencies]
alloy = { version = "0.13.0", default-features = false, features = ["contract", "sol-types"] }

[lib]
path = "src/mod.rs"
